//
//  DesignSystemImages+Glyphs.swift
//  Copyright © 2025 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

public extension DesignSystemImages {
    enum Glyphs {
        public enum Size12 {
            public static var aiChat: DesignSystemImage { .init(resource: .aiChat12) }
            public static var aiChatSolid: DesignSystemImage { .init(resource: .aiChatSolid12) }
            public static var app: DesignSystemImage { .init(resource: .app12) }
            public static var arrowCircleLeft: DesignSystemImage { .init(resource: .arrowCircleLeft12) }
            public static var arrowCircleRight: DesignSystemImage { .init(resource: .arrowCircleRight12) }
            public static var arrowCircleSolidLeft: DesignSystemImage { .init(resource: .arrowCircleSolidLeft12) }
            public static var arrowCircleSolidRight: DesignSystemImage { .init(resource: .arrowCircleSolidRight12) }
            public static var arrowDown: DesignSystemImage { .init(resource: .arrowDown12) }
            public static var arrowIndent: DesignSystemImage { .init(resource: .arrowIndent12) }
            public static var arrowLeft: DesignSystemImage { .init(resource: .arrowLeft12) }
            public static var arrowRight: DesignSystemImage { .init(resource: .arrowRight12) }
            public static var arrowUp: DesignSystemImage { .init(resource: .arrowUp12) }
            public static var assist: DesignSystemImage { .init(resource: .assist12) }
            public static var assistAlt: DesignSystemImage { .init(resource: .assistAlt12) }
            public static var audio: DesignSystemImage { .init(resource: .audio12) }
            public static var audioMute: DesignSystemImage { .init(resource: .audioMute12) }
            public static var battery: DesignSystemImage { .init(resource: .battery12) }
            public static var calendar: DesignSystemImage { .init(resource: .calendar12) }
            public static var car: DesignSystemImage { .init(resource: .car12) }
            public static var check: DesignSystemImage { .init(resource: .check12) }
            public static var chip: DesignSystemImage { .init(resource: .chip12) }
            public static var cookie: DesignSystemImage { .init(resource: .cookie12) }
            public static var currency: DesignSystemImage { .init(resource: .currency12) }
            public static var deviceMobile: DesignSystemImage { .init(resource: .deviceMobile12) }
            public static var download: DesignSystemImage { .init(resource: .download12) }
            public static var email: DesignSystemImage { .init(resource: .email12) }
            public static var exclamationSolid: DesignSystemImage { .init(resource: .exclamationSolid12) }
            public static var findSearch: DesignSystemImage { .init(resource: .findSearch12) }
            public static var fingerprint: DesignSystemImage { .init(resource: .fingerprint12) }
            public static var flag: DesignSystemImage { .init(resource: .flag12) }
            public static var globe: DesignSystemImage { .init(resource: .globe12) }
            public static var history: DesignSystemImage { .init(resource: .history12) }
            public static var info: DesignSystemImage { .init(resource: .info12) }
            public static var infoSolid: DesignSystemImage { .init(resource: .infoSolid12) }
            public static var location: DesignSystemImage { .init(resource: .location12) }
            public static var lockSolid: DesignSystemImage { .init(resource: .lockSolid12) }
            public static var maps: DesignSystemImage { .init(resource: .maps12) }
            public static var network: DesignSystemImage { .init(resource: .network12) }
            public static var night: DesignSystemImage { .init(resource: .night12) }
            public static var open: DesignSystemImage { .init(resource: .open12) }
            public static var options: DesignSystemImage { .init(resource: .options12) }
            public static var platform: DesignSystemImage { .init(resource: .platform12) }
            public static var policeBadge: DesignSystemImage { .init(resource: .policeBadge12) }
            public static var profile: DesignSystemImage { .init(resource: .profile12) }
            public static var sendPlane: DesignSystemImage { .init(resource: .sendPlane12) }
            public static var sensor: DesignSystemImage { .init(resource: .sensor12) }
            public static var settings: DesignSystemImage { .init(resource: .settings12) }
            public static var settingsSolid: DesignSystemImage { .init(resource: .settingsSolid12) }
            public static var shield: DesignSystemImage { .init(resource: .shield12E) }
            public static var shieldCheckAltColor: DesignSystemImage { .init(resource: .shieldCheckAltColor12E) }
            public static var shieldCheckColor: DesignSystemImage { .init(resource: .shieldCheckColor12E) }
            public static var shieldColor: DesignSystemImage { .init(resource: .shieldColor12E) }
            public static var shieldFilled: DesignSystemImage { .init(resource: .shieldFilled12E) }
            public static var storageCard: DesignSystemImage { .init(resource: .storageCard12) }
            public static var thumbsDown: DesignSystemImage { .init(resource: .thumbsDown12) }
            public static var thumbsUp: DesignSystemImage { .init(resource: .thumbsUp12) }
            public static var typeSize: DesignSystemImage { .init(resource: .typeSize12) }
            public static var wand: DesignSystemImage { .init(resource: .wand12) }
            public static var wifi: DesignSystemImage { .init(resource: .wifi12) }
        }

        public enum Size16 {
            public static var add: DesignSystemImage { .init(resource: .add16) }
            public static var addToHome: DesignSystemImage { .init(resource: .addToHome16) }
            public static var addToTaskbar: DesignSystemImage { .init(resource: .addToTaskbar16) }
            public static var aiChat: DesignSystemImage { .init(resource: .aiChat16) }
            public static var alert: DesignSystemImage { .init(resource: .alert16) }
            public static var alertRecolorable: DesignSystemImage { .init(resource: .alertRecolorable16) }
            public static var arrowCircleRight: DesignSystemImage { .init(resource: .arrowCircleRight16) }
            public static var arrowCircleDownLeft: DesignSystemImage { .init(resource: .arrowCircleDownLeft16) }
            public static var arrowCircleUpLeft: DesignSystemImage { .init(resource: .arrowCircleUpLeft16) }
            public static var arrowDown: DesignSystemImage { .init(resource: .arrowDown16) }
            public static var arrowUp: DesignSystemImage { .init(resource: .arrowUp16) }
            public static var assistAlt: DesignSystemImage { .init(resource: .assistAlt16) }
            public static var audio: DesignSystemImage { .init(resource: .audio16) }
            public static var audioMute: DesignSystemImage { .init(resource: .audioMute16) }
            public static var bookmark: DesignSystemImage { .init(resource: .bookmark16) }
            public static var bookmarkAdd: DesignSystemImage { .init(resource: .bookmarkAdd16) }
            public static var bookmarkAll: DesignSystemImage { .init(resource: .bookmarkAll16) }
            public static var bookmarkFavorite: DesignSystemImage { .init(resource: .bookmarkFavorite16) }
            public static var bookmarks: DesignSystemImage { .init(resource: .bookmarks16) }
            public static var bookmarkSolid: DesignSystemImage { .init(resource: .bookmarkSolid16) }
            public static var bookmarksSolid: DesignSystemImage { .init(resource: .bookmarksSolid16) }
            public static var browser: DesignSystemImage { .init(resource: .browser16) }
            public static var calendarWeek: DesignSystemImage { .init(resource: .calendarWeek16) }
            public static var check: DesignSystemImage { .init(resource: .check16) }
            public static var checkCircle: DesignSystemImage { .init(resource: .checkCircle16) }
            public static var checkGray: DesignSystemImage { .init(resource: .checkGray16) }
            public static var clear: DesignSystemImage { .init(resource: .clear16) }
            public static var clearSolid: DesignSystemImage { .init(resource: .clearSolid16) }
            public static var close: DesignSystemImage { .init(resource: .close16) }
            public static var closeSolidAlt: DesignSystemImage { .init(resource: .closeSolidAlt16) }
            public static var cookie: DesignSystemImage { .init(resource: .cookie16) }
            public static var cookieWhole: DesignSystemImage { .init(resource: .cookieWhole16) }
            public static var copy: DesignSystemImage { .init(resource: .copy16) }
            public static var currency: DesignSystemImage { .init(resource: .currency16) }
            public static var cut: DesignSystemImage { .init(resource: .cut16) }
            public static var deviceAll: DesignSystemImage { .init(resource: .deviceAll16) }
            public static var deviceDesktop: DesignSystemImage { .init(resource: .deviceDesktop16) }
            public static var deviceDesktopUnlock: DesignSystemImage { .init(resource: .deviceDesktopUnlock16) }
            public static var deviceLaptop: DesignSystemImage { .init(resource: .deviceLaptop16) }
            public static var deviceMobile: DesignSystemImage { .init(resource: .deviceMobile16) }
            public static var deviceMobileLock: DesignSystemImage { .init(resource: .deviceMobileLock16) }
            public static var dictionary: DesignSystemImage { .init(resource: .dictionary16) }
            public static var downloads: DesignSystemImage { .init(resource: .downloads16) }
            public static var edit: DesignSystemImage { .init(resource: .edit16) }
            public static var email: DesignSystemImage { .init(resource: .email16) }
            public static var emailBlocked: DesignSystemImage { .init(resource: .emailBlocked16) }
            public static var emailDisabled: DesignSystemImage { .init(resource: .emailDisabled16) }
            public static var emailForward: DesignSystemImage { .init(resource: .emailForward16) }
            public static var emailLocked: DesignSystemImage { .init(resource: .emailLocked16) }
            public static var emailUnlocked: DesignSystemImage { .init(resource: .emailUnlocked16) }
            public static var exclamation: DesignSystemImage { .init(resource: .exclamation16) }
            public static var export: DesignSystemImage { .init(resource: .export16) }
            public static var exportRight: DesignSystemImage { .init(resource: .exportRight16) }
            public static var eye: DesignSystemImage { .init(resource: .eye16) }
            public static var eyeClosed: DesignSystemImage { .init(resource: .eyeDisable16) }
            public static var favorite: DesignSystemImage { .init(resource: .favorite16) }
            public static var favoriteSolid: DesignSystemImage { .init(resource: .favoriteSolid16) }
            public static var feedback: DesignSystemImage { .init(resource: .feedback16) }
            public static var feedbackAlert: DesignSystemImage { .init(resource: .feedbackAlert16) }
            public static var findSearch: DesignSystemImage { .init(resource: .findSearch16) }
            public static var fire: DesignSystemImage { .init(resource: .fire16) }
            public static var fireSolid: DesignSystemImage { .init(resource: .fireSolid16) }
            public static var fireproof: DesignSystemImage { .init(resource: .fireproof16) }
            public static var fireproofSolid: DesignSystemImage { .init(resource: .fireproofSolid16) }
            public static var folder: DesignSystemImage { .init(resource: .folder16) }
            public static var folderDownloads: DesignSystemImage { .init(resource: .folderDownloads16) }
            public static var folderGoto: DesignSystemImage { .init(resource: .folderGoto16) }
            public static var folderMove: DesignSystemImage { .init(resource: .folderMove16) }
            public static var folderNew: DesignSystemImage { .init(resource: .folderNew16) }
            public static var gift: DesignSystemImage { .init(resource: .gift16) }
            public static var hourglass: DesignSystemImage { .init(resource: .hourglass16) }
            public static var imageCopy: DesignSystemImage { .init(resource: .imageCopy16) }
            public static var imageLink: DesignSystemImage { .init(resource: .imageLink16) }
            public static var `import`: DesignSystemImage { .init(resource: .import16) }
            public static var info: DesignSystemImage { .init(resource: .info16) }
            public static var infoRecolorable: DesignSystemImage { .init(resource: .infoRecolorable16) }
            public static var jump: DesignSystemImage { .init(resource: .jump16) }
            public static var jumpRecolorable: DesignSystemImage { .init(resource: .jumpRecolorable16) }
            public static var keyLogin: DesignSystemImage { .init(resource: .keyLogin16) }
            public static var linkRecolorable: DesignSystemImage { .init(resource: .linkRecolorable16) }
            public static var lock: DesignSystemImage { .init(resource: .lock16) }
            public static var locationSolid: DesignSystemImage { .init(resource: .locationSolid16) }
            public static var menuLinesDot: DesignSystemImage { .init(resource: .menuLinesDot16) }
            public static var microphoneBlocked: DesignSystemImage { .init(resource: .microphoneBlocked16) }
            public static var options: DesignSystemImage { .init(resource: .options16) }
            public static var pin: DesignSystemImage { .init(resource: .pin16) }
            public static var platformApple: DesignSystemImage { .init(resource: .platformApple16) }
            public static var platformMacOS: DesignSystemImage { .init(resource: .platformMacOS16) }
            public static var pointUpSolid: DesignSystemImage { .init(resource: .pointUpSolid16) }
            public static var print: DesignSystemImage { .init(resource: .print16) }
            public static var profile: DesignSystemImage { .init(resource: .profile16) }
            public static var qr: DesignSystemImage { .init(resource: .QR_16) }
            public static var recipe: DesignSystemImage { .init(resource: .recipe16) }
            public static var screenShare: DesignSystemImage { .init(resource: .screenShare16) }
            public static var screenShareBlocked: DesignSystemImage { .init(resource: .screenShareBlocked16) }
            public static var screenShareSolid: DesignSystemImage { .init(resource: .screenShareSolid16) }
            public static var searchSite: DesignSystemImage { .init(resource: .searchSite16) }
            public static var sendPlane: DesignSystemImage { .init(resource: .sendPlane16) }
            public static var setAsDefault: DesignSystemImage { .init(resource: .setAsDefault16) }
            public static var settings: DesignSystemImage { .init(resource: .settings16) }
            public static var shareApple: DesignSystemImage { .init(resource: .shareApple16) }
            public static var shield: DesignSystemImage { .init(resource: .shield16) }
            public static var shieldAlertAlt: DesignSystemImage { .init(resource: .shieldAlertAlt16) }
            public static var shieldBlocked: DesignSystemImage { .init(resource: .shieldBlocked16) }
            public static var sidebar: DesignSystemImage { .init(resource: .sidebar16) }
            public static var sidebarSearch: DesignSystemImage { .init(resource: .sidebarSearch16) }
            public static var siteBreakage: DesignSystemImage { .init(resource: .siteBreakage16) }
            public static var skipRecolorable: DesignSystemImage { .init(resource: .skipRecolorable16) }
            public static var sortAscending: DesignSystemImage { .init(resource: .sortAscending16) }
            public static var sortManually: DesignSystemImage { .init(resource: .sortManually16) }
            public static var support: DesignSystemImage { .init(resource: .support16) }
            public static var sync: DesignSystemImage { .init(resource: .sync16) }
            public static var systemTheme: DesignSystemImage { .init(resource: .systemTheme16) }
            public static var tabCloseAlt: DesignSystemImage { .init(resource: .tabCloseAlt16) }
            public static var tabMobile: DesignSystemImage { .init(resource: .tabMobile16) }
            public static var tabReopen: DesignSystemImage { .init(resource: .tabReopen16) }
            public static var tabTop: DesignSystemImage { .init(resource: .tabTop16) }
            public static var thumbsUp: DesignSystemImage { .init(resource: .thumbsUp16) }
            public static var trash: DesignSystemImage { .init(resource: .trash16) }
            public static var typeSize: DesignSystemImage { .init(resource: .typeSize16) }
            public static var videoSolid: DesignSystemImage { .init(resource: .videoSolid16) }
            public static var viewGrid: DesignSystemImage { .init(resource: .viewGrid16) }
            public static var viewGridSolid: DesignSystemImage { .init(resource: .viewGridSolid16) }
            public static var viewList: DesignSystemImage { .init(resource: .viewList16) }
            public static var viewListSolid: DesignSystemImage { .init(resource: .viewListSolid16) }
            public static var wand: DesignSystemImage { .init(resource: .wand16) }
            public static var weather: DesignSystemImage { .init(resource: .weather16) }
            public static var windowNew: DesignSystemImage { .init(resource: .windowNew16) }
            public static var windowsAndTabs: DesignSystemImage { .init(resource: .windowsAndTabs16) }
            public static var zoomActualSize: DesignSystemImage { .init(resource: .zoomActualSize16) }
        }

        public enum Size20 {
            public static var accessibility: DesignSystemImage { .init(resource: .accessibility20) }
            public static var accountsMultiple: DesignSystemImage { .init(resource: .accountsMultiple20) }
            public static var add: DesignSystemImage { .init(resource: .add20) }
            public static var arrowCircleDownLeft: DesignSystemImage { .init(resource: .arrowCircleDownLeft20) }
            public static var arrowCircleUpLeft: DesignSystemImage { .init(resource: .arrowCircleUpLeft20) }
            public static var arrowDownLeft: DesignSystemImage { .init(resource: .arrowDownLeft20) }
            public static var arrowDownRight: DesignSystemImage { .init(resource: .arrowDownRight20) }
            public static var arrowUpLeft: DesignSystemImage { .init(resource: .arrowUpLeft20) }
            public static var arrowUpRight: DesignSystemImage { .init(resource: .arrowUpRight20) }
            public static var assist: DesignSystemImage { .init(resource: .assist20) }
            public static var assistAlt: DesignSystemImage { .init(resource: .assistAlt20) }
            public static var bookmark: DesignSystemImage { .init(resource: .bookmark20) }
            public static var bookmarkFavorite: DesignSystemImage { .init(resource: .bookmarkFavorite20) }
            public static var bookmarkSolid: DesignSystemImage { .init(resource: .bookmarkSolid20) }
            public static var checkCircle: DesignSystemImage { .init(resource: .checkCircle20) }
            public static var checkRecolorable: DesignSystemImage { .init(resource: .checkRecolorable20) }
            public static var checkSolid: DesignSystemImage { .init(resource: .checkSolid20) }
            public static var chevronCircleDown: DesignSystemImage { .init(resource: .chevronCircleDown20) }
            public static var chevronCircleUp: DesignSystemImage { .init(resource: .chevronCircleUp20) }
            public static var closeRecolorable: DesignSystemImage { .init(resource: .closeRecolorable20) }
            public static var closeSolid: DesignSystemImage { .init(resource: .closeSolid20) }
            public static var copy: DesignSystemImage { .init(resource: .copy20) }
            public static var dashboard: DesignSystemImage { .init(resource: .dashboard20) }
            public static var downloads: DesignSystemImage { .init(resource: .downloads20) }
            public static var email: DesignSystemImage { .init(resource: .email20) }
            public static var emailDisabled: DesignSystemImage { .init(resource: .emailDisabled20) }
            public static var emoji: DesignSystemImage { .init(resource: .emoji20) }
            public static var exclamationRecolorable: DesignSystemImage { .init(resource: .exclamationRecolorable20) }
            public static var feedback: DesignSystemImage { .init(resource: .feedback20) }
            public static var findSearch: DesignSystemImage { .init(resource: .findSearch20) }
            public static var globe: DesignSystemImage { .init(resource: .globe20) }
            public static var history: DesignSystemImage { .init(resource: .history20) }
            public static var homepagePlain: DesignSystemImage { .init(resource: .homepagePlain20) }
            public static var info: DesignSystemImage { .init(resource: .info20) }
            public static var infoRecolorable: DesignSystemImage { .init(resource: .infoRecolorable20) }
            public static var infoSolid: DesignSystemImage { .init(resource: .infoSolid20) }
            public static var link: DesignSystemImage { .init(resource: .link20) }
            public static var linkRecolorable: DesignSystemImage { .init(resource: .linkRecolorable20) }
            public static var lock: DesignSystemImage { .init(resource: .lock20) }
            public static var lockUnlocked: DesignSystemImage { .init(resource: .lockUnlocked20) }
            public static var menuHamburger: DesignSystemImage { .init(resource: .menuHamburger20) }
            public static var microphone: DesignSystemImage { .init(resource: .microphone20) }
            public static var microphoneSolid: DesignSystemImage { .init(resource: .microphoneSolid20) }
            public static var privacyPro: DesignSystemImage { .init(resource: .privacyPro20) }
            public static var shield: DesignSystemImage { .init(resource: .shield20) }
            public static var shieldDisabled: DesignSystemImage { .init(resource: .shieldDisabled20) }
            public static var stop: DesignSystemImage { .init(resource: .stop20) }
            public static var stopRecolorable: DesignSystemImage { .init(resource: .stopRecolorable20) }
            public static var stopSolid: DesignSystemImage { .init(resource: .stopSolid20) }
            public static var tab: DesignSystemImage { .init(resource: .tab20) }
            public static var upload: DesignSystemImage { .init(resource: .upload20) }
            public static var uploadFile: DesignSystemImage { .init(resource: .uploadFile20) }
            public static var videoPlaySolid: DesignSystemImage { .init(resource: .videoPlaySolid20) }
            public static var wand: DesignSystemImage { .init(resource: .wand20) }
        }

        public enum Size24 {
            public static var accessibility: DesignSystemImage { .init(resource: .accessibility24) }
            public static var add: DesignSystemImage { .init(resource: .add24) }
            public static var addition: DesignSystemImage { .init(resource: .addition24) }
            public static var aiChat: DesignSystemImage { .init(resource: .aiChat24) }
            public static var aiChatAddSolid: DesignSystemImage { .init(resource: .aiChatAddSolid24) }
            public static var alertRecolorable: DesignSystemImage { .init(resource: .alertRecolorable24) }
            public static var arrowCircleUpLeft: DesignSystemImage { .init(resource: .arrowCircleUpLeft24) }
            public static var arrowDownLeft: DesignSystemImage { .init(resource: .arrowDownLeft24) }
            public static var arrowDownRight: DesignSystemImage { .init(resource: .arrowDownRight24) }
            public static var arrowDownLeftSmall: DesignSystemImage { .init(resource: .arrowDownLeft24Small) }
            public static var arrowLeft: DesignSystemImage { .init(resource: .arrowLeft24) }
            public static var arrowLeftSmall: DesignSystemImage { .init(resource: .arrowLeftSmall24) }
            public static var arrowRight: DesignSystemImage { .init(resource: .arrowRight24) }
            public static var arrowUp: DesignSystemImage { .init(resource: .arrowUp24) }
            public static var arrowUpRight: DesignSystemImage { .init(resource: .arrowUpRight24) }
            public static var assistAlt: DesignSystemImage { .init(resource: .assistAlt24) }
            public static var bell: DesignSystemImage { .init(resource: .bell24) }
            public static var bookmarks: DesignSystemImage { .init(resource: .bookmarks24) }
            public static var bookmarkNew: DesignSystemImage { .init(resource: .bookmarkNew24) }
            public static var bookmarkRecolorable: DesignSystemImage { .init(resource: .bookmarkRecolorable24) }
            public static var bookmarksList: DesignSystemImage { .init(resource: .bookmarksList24) }
            public static var bookmarksOpen: DesignSystemImage { .init(resource: .bookmarksOpen24) }
            public static var calendar: DesignSystemImage { .init(resource: .calendar24) }
            public static var card: DesignSystemImage { .init(resource: .card24) }
            public static var checkRecolorable: DesignSystemImage { .init(resource: .checkRecolorable24) }
            public static var checkCircle: DesignSystemImage { .init(resource: .checkCircle24) }
            public static var chevronCircleDown: DesignSystemImage { .init(resource: .chevronCircleDown24) }
            public static var chevronDown: DesignSystemImage { .init(resource: .chevronDown24) }
            public static var chevronDownSmall: DesignSystemImage { .init(resource: .chevronDown24Small) }
            public static var chevronLeftSmall: DesignSystemImage { .init(resource: .chevronLeft24Small) }
            public static var chevronRightSmall: DesignSystemImage { .init(resource: .chevronRight24Small) }
            public static var chevronUpSmall: DesignSystemImage { .init(resource: .chevronUp24Small) }
            public static var close: DesignSystemImage { .init(resource: .close24) }
            public static var closeCircleSmall: DesignSystemImage { .init(resource: .closeCircleSmall24) }
            public static var clear: DesignSystemImage { .init(resource: .clear24) }
            public static var cookie: DesignSystemImage { .init(resource: .cookie24) }
            public static var cookieWhole: DesignSystemImage { .init(resource: .cookieWhole24) }
            public static var copy: DesignSystemImage { .init(resource: .copy24) }
            public static var covid: DesignSystemImage { .init(resource: .covid24) }
            public static var crossRecolorable: DesignSystemImage { .init(resource: .crossRecolorable24) }
            public static var crossSolidSmall: DesignSystemImage { .init(resource: .crossSolidSmall24) }
            public static var cut: DesignSystemImage { .init(resource: .cut24) }
            public static var deviceMobileDouble: DesignSystemImage { .init(resource: .deviceMobileDouble24) }
            public static var documentNew: DesignSystemImage { .init(resource: .documentNew24) }
            public static var documentReplace: DesignSystemImage { .init(resource: .documentReplace24) }
            public static var downloads: DesignSystemImage { .init(resource: .downloads24) }
            public static var duckDuckGoDaxColor: DesignSystemImage { .init(resource: .duckDuckGoDaxColor24) }
            public static var duckDuckGoDaxGreyscale: DesignSystemImage { .init(resource: .duckDuckGoDaxGreyscale24) }
            public static var edit: DesignSystemImage { .init(resource: .edit24) }
            public static var email: DesignSystemImage { .init(resource: .email24) }
            public static var emailCheck: DesignSystemImage { .init(resource: .emailCheck24) }
            public static var emailForward: DesignSystemImage { .init(resource: .emailForward24) }
            public static var eye: DesignSystemImage { .init(resource: .eye24) }
            public static var eyeClosed: DesignSystemImage { .init(resource: .eyeClosed24) }
            public static var exclamation: DesignSystemImage { .init(resource: .exclamation24) }
            public static var exclamationSolid: DesignSystemImage { .init(resource: .exclamationSolid24) }
            public static var favorite: DesignSystemImage { .init(resource: .favorite24) }
            public static var favoriteRemove: DesignSystemImage { .init(resource: .favoriteRemove24) }
            public static var favoriteSolid: DesignSystemImage { .init(resource: .favoriteSolid24) }
            public static var findSearchSmall: DesignSystemImage { .init(resource: .findSearchSmall24) }
            public static var fire: DesignSystemImage { .init(resource: .fire24) }
            public static var fireSolid: DesignSystemImage { .init(resource: .fireSolid24) }
            public static var fireproof: DesignSystemImage { .init(resource: .fireproof24) }
            public static var fireproof1: DesignSystemImage { .init(resource: .fireproof241) }
            public static var folder: DesignSystemImage { .init(resource: .folder24) }
            public static var folderAdd: DesignSystemImage { .init(resource: .folderAdd24) }
            public static var folderGoTo: DesignSystemImage { .init(resource: .folderGoTo24) }
            public static var folderMove: DesignSystemImage { .init(resource: .folderMove24) }
            public static var fontSmaller: DesignSystemImage { .init(resource: .fontSmaller24) }
            public static var fontLarger: DesignSystemImage { .init(resource: .fontLarger24) }
            public static var gift: DesignSystemImage { .init(resource: .gift24) }
            public static var globe: DesignSystemImage { .init(resource: .globe24) }
            public static var goTo: DesignSystemImage { .init(resource: .goTo24) }
            public static var help: DesignSystemImage { .init(resource: .help24) }
            public static var history: DesignSystemImage { .init(resource: .history24) }
            public static var identityTheftRestoration: DesignSystemImage { .init(resource: .identityTheftRestoration24) }
            public static var image: DesignSystemImage { .init(resource: .image24) }
            public static var info: DesignSystemImage { .init(resource: .info24) }
            public static var key: DesignSystemImage { .init(resource: .key24) }
            public static var linkSolid: DesignSystemImage { .init(resource: .linkSolid24) }
            public static var location: DesignSystemImage { .init(resource: .location24) }
            public static var locationBlocked: DesignSystemImage { .init(resource: .locationBlocked24) }
            public static var locationSolid: DesignSystemImage { .init(resource: .locationSolid24) }
            public static var menuHamburger: DesignSystemImage { .init(resource: .menuHamburger24) }
            public static var menuHamburgerAlertRecolorable: DesignSystemImage { .init(resource: .menuHamburgerAlertRecolorable24) }
            public static var microphone: DesignSystemImage { .init(resource: .microphone24) }
            public static var microphoneSolid: DesignSystemImage { .init(resource: .microphoneSolid24) }
            public static var minus: DesignSystemImage { .init(resource: .minus24) }
            public static var moreApple: DesignSystemImage { .init(resource: .moreApple24) }
            public static var news: DesignSystemImage { .init(resource: .news24) }
            public static var note: DesignSystemImage { .init(resource: .note24) }
            public static var openIn: DesignSystemImage { .init(resource: .openIn24) }
            public static var paste: DesignSystemImage { .init(resource: .paste24) }
            public static var phone: DesignSystemImage { .init(resource: .phone24) }
            public static var platformPlayStore: DesignSystemImage { .init(resource: .platformPlayStore24) }
            public static var pointUp: DesignSystemImage { .init(resource: .pointUp24) }
            public static var pointUpSolid: DesignSystemImage { .init(resource: .pointUpSolid24) }
            public static var reload: DesignSystemImage { .init(resource: .reload24) }
            public static var rename: DesignSystemImage { .init(resource: .rename24) }
            public static var replace: DesignSystemImage { .init(resource: .replace24) }
            public static var reset: DesignSystemImage { .init(resource: .reset24) }
            public static var resetSites: DesignSystemImage { .init(resource: .resetSites24) }
            public static var settings: DesignSystemImage { .init(resource: .settings24) }
            public static var shapeCircle: DesignSystemImage { .init(resource: .shapeCircle24) }
            public static var shareAndroid: DesignSystemImage { .init(resource: .shareAndroid24) }
            public static var shareApple: DesignSystemImage { .init(resource: .shareApple24) }
            public static var shortcut: DesignSystemImage { .init(resource: .shortcut24) }
            public static var sortAccending: DesignSystemImage { .init(resource: .sortAccending24) }
            public static var subItem: DesignSystemImage { .init(resource: .subItem24) }
            public static var subItemRecolorable: DesignSystemImage { .init(resource: .subItemRecolorable24) }
            public static var subtraction: DesignSystemImage { .init(resource: .subtraction24) }
            public static var support: DesignSystemImage { .init(resource: .support24) }
            public static var syncCloud: DesignSystemImage { .init(resource: .syncCloud24) }
            public static var tabMobile: DesignSystemImage { .init(resource: .tabMobile24) }
            public static var tabMobileAlertRecolorable: DesignSystemImage { .init(resource: .tabMobileAlertRecolorable24) }
            public static var tabMobileAlertDot: DesignSystemImage { .init(resource: .tabMobileAlertDot24) }
            public static var tabNew: DesignSystemImage { .init(resource: .tabNew24) }
            public static var tag: DesignSystemImage { .init(resource: .tag24) }
            public static var trash: DesignSystemImage { .init(resource: .trash24) }
            public static var typeSize: DesignSystemImage { .init(resource: .typeSize24) }
            public static var vpn: DesignSystemImage { .init(resource: .VPN_24) }
            public static var video: DesignSystemImage { .init(resource: .video24) }
            public static var videoPlayer: DesignSystemImage { .init(resource: .videoPlayer24) }
            public static var videoSolid: DesignSystemImage { .init(resource: .videoSolid24) }
            public static var viewGrid: DesignSystemImage { .init(resource: .viewGrid24) }
            public static var zoomIn: DesignSystemImage { .init(resource: .zoomIn24) }
       }
   }
}
